from fpdf import FPDF
import re
import logging
from datetime import datetime
from typing import Optional

logger = logging.getLogger(__name__)


class EduBotPDF(FPDF):
    def __init__(self, title: str = "EduBot Study Notes"):
        super().__init__()
        self.title_text = title
        self.set_auto_page_break(auto=True, margin=15)

    def header(self):
        self.set_font("Helvetica", "B", 14)
        self.set_fill_color(99, 102, 241)
        self.set_text_color(255, 255, 255)
        self.cell(0, 12, f"  EduBot - {self.title_text}", fill=True, ln=True, align="L")
        self.set_text_color(0, 0, 0)
        self.ln(4)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f"Generated by EduBot | {datetime.now().strftime('%Y-%m-%d %H:%M')} | Page {self.page_no()}", align="C")

    def section_title(self, title: str):
        self.set_font("Helvetica", "B", 12)
        self.set_fill_color(237, 233, 254)
        self.set_text_color(79, 70, 229)
        self.cell(0, 9, f"  {title}", fill=True, ln=True)
        self.set_text_color(0, 0, 0)
        self.ln(2)

    def body_text(self, text: str):
        self.set_font("Helvetica", "", 10)
        self.set_text_color(40, 40, 40)
        clean = self._clean_markdown(text)
        self.multi_cell(0, 6, clean)
        self.ln(2)

    def code_block(self, code: str):
        self.set_font("Courier", "", 9)
        self.set_fill_color(245, 245, 245)
        self.set_text_color(30, 30, 30)
        lines = code.split("\n")
        for line in lines[:40]:
            self.cell(0, 5, line[:120], fill=True, ln=True)
        self.set_text_color(0, 0, 0)
        self.ln(2)

    def _clean_markdown(self, text: str) -> str:
        text = re.sub(r"```[\w]*\n?", "", text)
        text = re.sub(r"\*\*(.+?)\*\*", r"\1", text)
        text = re.sub(r"\*(.+?)\*", r"\1", text)
        text = re.sub(r"#{1,6}\s+", "", text)
        text = re.sub(r"`(.+?)`", r"\1", text)
        text = re.sub(r"\[(.+?)\]\(.+?\)", r"\1", text)
        text = re.sub(r"[^\x00-\x7F]+", lambda m: m.group().encode("latin-1", "replace").decode("latin-1"), text)
        return text.strip()


def generate_chat_notes_pdf(
    messages: list,
    session_title: str,
    subject: Optional[str],
    language: str,
    username: str,
) -> bytes:
    pdf = EduBotPDF(title=session_title)
    pdf.add_page()

    pdf.set_font("Helvetica", "B", 11)
    pdf.set_fill_color(250, 249, 255)
    pdf.cell(0, 8, f"Subject: {subject or 'General'}  |  Language: {language}  |  Student: {username}", fill=True, ln=True)
    pdf.ln(4)

    for i, msg in enumerate(messages):
        if msg["role"] == "user":
            pdf.section_title(f"Question {(i // 2) + 1}")
            pdf.body_text(msg["content"])
        else:
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(16, 185, 129)
            pdf.cell(0, 7, "EduBot Answer:", ln=True)
            pdf.set_text_color(0, 0, 0)

            content = msg["content"]
            code_pattern = re.compile(r"```(\w*)\n?(.*?)```", re.DOTALL)
            last_end = 0
            for match in code_pattern.finditer(content):
                if match.start() > last_end:
                    pdf.body_text(content[last_end : match.start()])
                pdf.code_block(match.group(2))
                last_end = match.end()
            if last_end < len(content):
                pdf.body_text(content[last_end:])

        pdf.ln(2)

    return bytes(pdf.output())


def generate_quiz_pdf(quiz_data: dict, username: str) -> bytes:
    pdf = EduBotPDF(title=f"Quiz - {quiz_data.get('subject', 'Engineering')}")
    pdf.add_page()

    pdf.set_font("Helvetica", "B", 11)
    score = quiz_data.get("score")
    score_text = f"Score: {score:.1f}%" if score is not None else "Not completed"
    pdf.cell(0, 8, f"Student: {username}  |  {score_text}  |  Difficulty: {quiz_data.get('difficulty', 'N/A')}", ln=True)
    pdf.ln(4)

    for i, q in enumerate(quiz_data.get("questions", []), 1):
        pdf.section_title(f"Question {i}")
        pdf.body_text(q.get("question_text", ""))

        opts = q.get("options", {})
        for key, val in opts.items():
            is_correct = key == q.get("correct_answer")
            is_user = key == q.get("user_answer")
            marker = " ✓" if is_correct else (" ✗" if is_user and not is_correct else "")
            pdf.set_font("Helvetica", "", 10)
            pdf.cell(0, 6, f"  {key}. {val}{marker}", ln=True)

        if q.get("explanation"):
            pdf.set_font("Helvetica", "I", 9)
            pdf.set_text_color(100, 100, 100)
            pdf.multi_cell(0, 5, f"Explanation: {q['explanation']}")
            pdf.set_text_color(0, 0, 0)
        pdf.ln(3)

    return bytes(pdf.output())
